### ISSUE TITLE
This model has incomplete visualization 

### ISSUE THREAD

**Issue by xuzhongxing** [fougue/mayo#101]
This might be a bug of OCCT.
![occt](https://user-images.githubusercontent.com/5483073/154212081-f873fca0-ae7c-424d-a07e-42e229e1b30f.png)
![acis3](https://user-images.githubusercontent.com/5483073/154212092-2e55e3b1-b46e-4f73-b2ed-73f2bec502f8.png)

**Comment by HuguesDelorme** [comment]
Hello, can you provide the model as an attached piece here ?
Or a download link if it's too big ?
