### ISSUE TITLE
Black 3D window when opening file with version 0.5.1

### ISSUE THREAD

**Issue by younghang** [fougue/mayo#109]
![image](https://user-images.githubusercontent.com/12094269/156512416-68ffe6ac-9448-4098-94b4-f686f75c15db.png)
When I am using version 0.4 everything is OK, I got black screen when I update the mayo to version 0.5.1. I can't see anything in the model window. I don't know what is wrong.

**Comment by HuguesDelorme** [comment]
Fixed with commit https://github.com/fougue/mayo/commit/3510c932d9e31a9e7d2f160874ed42b42d13759e

**Comment by HuguesDelorme** [comment]
@younghang
Please install bugfix release v0.5.2 and let me know if that problem is solved on your side
https://github.com/fougue/mayo/releases/download/v0.5.2/mayo_v0.5.2.860-2f9229e_winx64_installer.exe

**Comment by younghang** [comment]
@HuguesDelorme It has been solved. Thanks. But I feel it becomes less fluent, maybe it is my illusion.

**Comment by HuguesDelorme** [comment]
@younghang
To verify the potential slowdown, you can activate performance stats by clicking on menu "Display->Show Performance Stats" and check the FPS
If you have both 0.4 and 0.5.2 versions installed it would be interesting to compare.
