### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by yvanblanchard** [fougue/mayo#112]
Hello,

I have some link errors (see image below).
I am using:
Qt Creator 4.13.2, with QT v5.13.2, and MSVC2017 x64.
Open-Cascade v7.6.0.

![image](https://user-images.githubusercontent.com/63931618/157289077-49b0b996-22c6-48de-b5f3-6c16b8a77b1c.png)

Could you please help ?
Thank you.

**Comment by HuguesDelorme** [comment]
Are you trying to build latest commit in develop branch?
I can't see what could cause these errors as the appveyor CI config is nearly the same as yours.
See:
https://github.com/fougue/mayo/blob/develop/appveyor.yml
https://ci.appveyor.com/project/HuguesDelorme/mayo/build/job/o1ju2kbc0rxhep5i

I would recommend to clean output build directory and run QMake step again.

**Comment by HuguesDelorme** [comment]
@yvanblanchard did you manage to solve those errors ?

**Comment by yvanblanchard** [comment]
@HuguesDelorme Unfortunately, I still have those linking errors, even after cleaning the build directory..

**Comment by HuguesDelorme** [comment]
There's certainly an issue with your git clone because `io_occ_obj.cpp` is no longer in Mayo codebase.
Try to run "git clean -dxf"
If the error persists then I would recommend to clone Mayo again

**Comment by yvanblanchard** [comment]
Hello
Thank you. Cloning the repo again solved the issue
