### ISSUE TITLE
Set application icon on macOS

### ISSUE THREAD

**Issue by HuguesDelorme** [fougue/mayo#122]
Use this procedure:
    https://doc.qt.io/qt-5/appicon.html#setting-the-application-icon-on-macos

**Comment by andrsd** [comment]
Attached patch should do the trick for the qmake-based build.

With the patch, I can see the icon on macOS. See these 2 screenshots: (1) from the dock, (2) from switching between apps.

<img width="80" alt="image" src="https://user-images.githubusercontent.com/85632/228956303-0b15cb79-f769-4529-bd8c-80235e275b5e.png"><img width="128" alt="image" src="https://user-images.githubusercontent.com/85632/228956956-63f9420e-90b4-4a47-9c2a-eb6aa8e462d4.png">

Feel free to adjust the patch to your liking. 

[0001-Generate-icon-for-the-.app-bundle.patch](https://github.com/fougue/mayo/files/11115824/0001-Generate-icon-for-the-.app-bundle.patch)

**Comment by andrsd** [comment]
I just saw #53 , so if you are interested how to do this with cmake, see this [CMakeLists.txt](https://github.com/andrsd/mesh-inspector/blob/main/src/CMakeLists.txt). It is one of my Qt-based projects. It is very short and should be pretty self-explanatory. I used that for the patch I sent earlier.

**Comment by HuguesDelorme** [comment]
@andrsd
Thank you for the patch
I think it would be preferrable to generate once `icon.icns` file and put it under version control
Your patch is really fine because it shows the steps to produce that file from existing `appicon_256.png`
By the way could that file be renamed to `appicon_256.icns` ?

That would be so great if you could prepare a pull request for this!
Let me know if you agree with that

**Comment by andrsd** [comment]
> By the way could that file be renamed to `appicon_256.icns` ?

I think the name can be what ever. The `ICON = filename` directive will put that `filename` into the plist file which is what  tells macOS which file it should look for.

Note that `.icns` file does not hold only a single icon, but a set of icons of different sizes.  I only put the largest one in it in my patch.  If you want to have the `.icns` file under version control, I can put all the `.png`s with different sizes in the `icns` file for you. Then, I think it would be appropriate to name the file `appicon.icns`. What do you think?

**Comment by HuguesDelorme** [comment]
@andrsd

> (...) I can put all the `.png`s with different sizes in the `icns` file
(...) I think it would be appropriate to name the file `appicon.icns`

That sounds the way to go!
Waiting to merge your coming pull request, thanks again!
