### ISSUE TITLE
CATIA mouse settings

### ISSUE THREAD

**Issue by yvanblanchard** [fougue/mayo#123]
Hello,

could it be possible to use CATIA V5 settings for mouse (pan, rotate, rotation center,..) ? It would be very useful.

Thank you.

**Comment by HuguesDelorme** [comment]
Yes that should be rather easy to implement.
Can you please provide here the detailed mouse/keyboard settings to control the 3D view in CATIA ?

**Comment by yvanblanchard** [comment]
That’s a good new.
Here is a link to the Abaqus cae documentation, with view mouse settings description (including catia and solid works).
Thank you again, your software is very nice and helpful.

**Comment by HuguesDelorme** [comment]
Duplicated by #125

**Comment by HuguesDelorme** [comment]
@yvanblanchard 
Can you please test latest Mayo and report feedback regarding this feature?

**Comment by yvanblanchard** [comment]
I just tested and it works nice !
Thank you. Great improvement !
