### ISSUE TITLE
Which version of Qt is used? Is msvc2017?

### ISSUE THREAD

**Issue by jinlong631** [fougue/mayo#13]
Which version of Qt is used? Is msvc2017?

**Comment by HuguesDelorme** [comment]
Hello!
The source code relies on Qt5, about the minimal version I can't tell for sure. On my workstation Mayo builds fine with Qt 5.11 and 5.13 but it is surely compatible with older versions.
And yes you can build with MSVC 2017 on Windows, actually this is the compiler I currently use.

**Comment by jinlong631** [comment]
> Hello!
> The source code relies on Qt5, about the minimal version I can't tell for sure. On my workstation Mayo builds fine with Qt 5.11 and 5.13 but it is surely compatible with older versions.
> And yes you can build with MSVC 2017 on Windows, actually this is the compiler I currently use.

Okay thank you
