### ISSUE TITLE
Update Windows Build Documentation

### ISSUE THREAD

**Issue by jingliang2005** [fougue/mayo#136]
https://github.com/fougue/mayo/wiki/Build-instructions-for-Windows-MSVC

Add Qt Creator Build:

call "C:\Libs\OpenCASCADE-7.6.0-vc14-64\opencascade-7.6.0\env.bat"
cd C:\Qt\Qt5\Tools\QtCreator\bin
qtcreator.exe

In Qt Creator Open mayo.pro

**Comment by HuguesDelorme** [comment]
Added this note in the mentionned wiki page:
_Before executing Visual Studio make sure `%QTDIR%\bin` is in `PATH` and `%OCCDIR%\env.bat` was called. Notice this is relevant for any IDE(eg QtCreator) and not limited to Visual Studio only._
