### ISSUE TITLE
Getting errors compiling mayo

### ISSUE THREAD

**Issue by devds** [fougue/mayo#139]
Hi, I am compiling mayo with :
1. Visual Studio CE 2022
2.Qt 6.2
3. OCCT 7.6

I get the following unresolved externals:

1>------ Build started: Project: mayo, Configuration: Release x64 ------
1>   Creating library release\\mayo.lib and object release\\mayo.exp
1>io_occ.obj : error LNK2019: unresolved external symbol "public: __cdecl Mayo::IO::OccGltfReader::OccGltfReader(void)" (??0OccGltfReader@IO@Mayo@@QEAA@XZ) referenced in function "class std::unique_ptr<class Mayo::IO::OccGltfReader,struct std::default_delete<class Mayo::IO::OccGltfReader> > __cdecl std::make_unique<class Mayo::IO::OccGltfReader,0>(void)" (??$make_unique@VOccGltfReader@IO@Mayo@@$$V$0A@@std@@YA?AV?$unique_ptr@VOccGltfReader@IO@Mayo@@U?$default_delete@VOccGltfReader@IO@Mayo@@@std@@@0@XZ)
1>io_occ.obj : error LNK2019: unresolved external symbol "public: static class std::unique_ptr<class Mayo::PropertyGroup,struct std::default_delete<class Mayo::PropertyGroup> > __cdecl Mayo::IO::OccGltfReader::createProperties(class Mayo::PropertyGroup *)" (?createProperties@OccGltfReader@IO@Mayo@@SA?AV?$unique_ptr@VPropertyGroup@Mayo@@U?$default_delete@VPropertyGroup@Mayo@@@std@@@std@@PEAVPropertyGroup@3@@Z) referenced in function "public: virtual class std::unique_ptr<class Mayo::PropertyGroup,struct std::default_delete<class Mayo::PropertyGroup> > __cdecl Mayo::IO::OccFactoryReader::createProperties(enum Mayo::IO::Format,class Mayo::PropertyGroup *)const " (?createProperties@OccFactoryReader@IO@Mayo@@UEBA?AV?$unique_ptr@VPropertyGroup@Mayo@@U?$default_delete@VPropertyGroup@Mayo@@@std@@@std@@W4Format@23@PEAVPropertyGroup@3@@Z)
1>io_occ.obj : error LNK2019: unresolved external symbol "public: __cdecl Mayo::IO::OccObjReader::OccObjReader(void)" (??0OccObjReader@IO@Mayo@@QEAA@XZ) referenced in function "class std::unique_ptr<class Mayo::IO::OccObjReader,struct std::default_delete<class Mayo::IO::OccObjReader> > __cdecl std::make_unique<class Mayo::IO::OccObjReader,0>(void)" (??$make_unique@VOccObjReader@IO@Mayo@@$$V$0A@@std@@YA?AV?$unique_ptr@VOccObjReader@IO@Mayo@@U?$default_delete@VOccObjReader@IO@Mayo@@@std@@@0@XZ)
1>io_occ.obj : error LNK2019: unresolved external symbol "public: static class std::unique_ptr<class Mayo::PropertyGroup,struct std::default_delete<class Mayo::PropertyGroup> > __cdecl Mayo::IO::OccObjReader::createProperties(class Mayo::PropertyGroup *)" (?createProperties@OccObjReader@IO@Mayo@@SA?AV?$unique_ptr@VPropertyGroup@Mayo@@U?$default_delete@VPropertyGroup@Mayo@@@std@@@std@@PEAVPropertyGroup@3@@Z) referenced in function "public: virtual class std::unique_ptr<class Mayo::PropertyGroup,struct std::default_delete<class Mayo::PropertyGroup> > __cdecl Mayo::IO::OccFactoryReader::createProperties(enum Mayo::IO::Format,class Mayo::PropertyGroup *)const " (?createProperties@OccFactoryReader@IO@Mayo@@UEBA?AV?$unique_ptr@VPropertyGroup@Mayo@@U?$default_delete@VPropertyGroup@Mayo@@@std@@@std@@W4Format@23@PEAVPropertyGroup@3@@Z)
1>io_occ.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl Mayo::IO::OccGltfWriter::transfer(class gsl::span<class Mayo::ApplicationItem const ,-1>,class Mayo::TaskProgress *)" (?transfer@OccGltfWriter@IO@Mayo@@UEAA_NV?$span@$$CBVApplicationItem@Mayo@@$0?0@gsl@@PEAVTaskProgress@3@@Z)
1>io_occ.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl Mayo::IO::OccGltfWriter::writeFile(class std::filesystem::path const &,class Mayo::TaskProgress *)" (?writeFile@OccGltfWriter@IO@Mayo@@UEAA_NAEBVpath@filesystem@std@@PEAVTaskProgress@3@@Z)
1>io_occ.obj : error LNK2019: unresolved external symbol "public: static class std::unique_ptr<class Mayo::PropertyGroup,struct std::default_delete<class Mayo::PropertyGroup> > __cdecl Mayo::IO::OccGltfWriter::createProperties(class Mayo::PropertyGroup *)" (?createProperties@OccGltfWriter@IO@Mayo@@SA?AV?$unique_ptr@VPropertyGroup@Mayo@@U?$default_delete@VPropertyGroup@Mayo@@@std@@@std@@PEAVPropertyGroup@3@@Z) referenced in function "public: virtual class std::unique_ptr<class Mayo::PropertyGroup,struct std::default_delete<class Mayo::PropertyGroup> > __cdecl Mayo::IO::OccFactoryWriter::createProperties(enum Mayo::IO::Format,class Mayo::PropertyGroup *)const " (?createProperties@OccFactoryWriter@IO@Mayo@@UEBA?AV?$unique_ptr@VPropertyGroup@Mayo@@U?$default_delete@VPropertyGroup@Mayo@@@std@@@std@@W4Format@23@PEAVPropertyGroup@3@@Z)
1>io_occ.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl Mayo::IO::OccGltfWriter::applyProperties(class Mayo::PropertyGroup const *)" (?applyProperties@OccGltfWriter@IO@Mayo@@UEAAXPEBVPropertyGroup@3@@Z)
1>io_occ.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl Mayo::IO::OccObjWriter::transfer(class gsl::span<class Mayo::ApplicationItem const ,-1>,class Mayo::TaskProgress *)" (?transfer@OccObjWriter@IO@Mayo@@UEAA_NV?$span@$$CBVApplicationItem@Mayo@@$0?0@gsl@@PEAVTaskProgress@3@@Z)
1>io_occ.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl Mayo::IO::OccObjWriter::writeFile(class std::filesystem::path const &,class Mayo::TaskProgress *)" (?writeFile@OccObjWriter@IO@Mayo@@UEAA_NAEBVpath@filesystem@std@@PEAVTaskProgress@3@@Z)
1>io_occ.obj : error LNK2019: unresolved external symbol "public: static class std::unique_ptr<class Mayo::PropertyGroup,struct std::default_delete<class Mayo::PropertyGroup> > __cdecl Mayo::IO::OccObjWriter::createProperties(class Mayo::PropertyGroup *)" (?createProperties@OccObjWriter@IO@Mayo@@SA?AV?$unique_ptr@VPropertyGroup@Mayo@@U?$default_delete@VPropertyGroup@Mayo@@@std@@@std@@PEAVPropertyGroup@3@@Z) referenced in function "public: virtual class std::unique_ptr<class Mayo::PropertyGroup,struct std::default_delete<class Mayo::PropertyGroup> > __cdecl Mayo::IO::OccFactoryWriter::createProperties(enum Mayo::IO::Format,class Mayo::PropertyGroup *)const " (?createProperties@OccFactoryWriter@IO@Mayo@@UEBA?AV?$unique_ptr@VPropertyGroup@Mayo@@U?$default_delete@VPropertyGroup@Mayo@@@std@@@std@@W4Format@23@PEAVPropertyGroup@3@@Z)
1>io_occ.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl Mayo::IO::OccObjWriter::applyProperties(class Mayo::PropertyGroup const *)" (?applyProperties@OccObjWriter@IO@Mayo@@UEAAXPEBVPropertyGroup@3@@Z)
1>release\\mayo.exe : fatal error LNK1120: 12 unresolved externals
1>Done building project "mayo.vcxproj" -- FAILED.

How can I fix?
Thanks in advance

**Comment by HuguesDelorme** [comment]
How did you generate mayo.vcxproj ?
What was your command-line ?

**Comment by devds** [comment]
From Visual Studio 2022  Menu->Extension -> Qt Vs Tools -> Open Qt Project ( . pro)

**Comment by devds** [comment]
Hello, it runs ! I have follwed instructions the link
Thanks

**Comment by devds** [comment]
Congrat for Mayo.
I have starred
