### ISSUE TITLE
Support reading of 3MF files

### ISSUE THREAD

**Issue by HuguesDelorme** [fougue/mayo#146]
Implement reading of 3MF files.

From @tpimh :
- https://en.wikipedia.org/wiki/3D_Manufacturing_Format
- https://docs.fileformat.com/3d/3mf/
- https://3mf.io/specification/
- https://github.com/3MFConsortium/lib3mf

**Comment by tpimh** [comment]
In my opinion, 3MF is way better documented than AMF. Since both formats try to solve the same problems, but 3MF is newer and is being developed more actively. I can't tell which format is more widely adopted.

**Comment by tpimh** [comment]
I just tested the new release, and 3MF import worked. No color support, but the geometry is rendered correctly.
