### ISSUE TITLE
Support reading of AMF files

### ISSUE THREAD

**Issue by HuguesDelorme** [fougue/mayo#147]
Implement reading of AMF files.

From @tpimh :
- https://en.wikipedia.org/wiki/Additive_manufacturing_file_format
- https://docs.fileformat.com/3d/amf/
- https://materialseducation.org/educators/matedu-modules/docs/AM_Module-AMF_Format.pdf

Note: OpenCascade doesn't provide AMF import

**Comment by tpimh** [comment]
CAD Assistant [claims to support](https://www.opencascade.com/release_notes/cad-assistant/) AMF import:

> Version 1.1 (August 10, 2018)
> - New mesh import formats (WRL1, BLEND, 3MF, 3DM, 3DS, AC3D, **AMF**, ASE, COLLADA, X3D).
