### ISSUE TITLE
Convert mouse position to world coordinates

### ISSUE THREAD

**Issue by sbabadag** [fougue/mayo#15]
hi;
the V3dView_to3dPosition function works only if there is an object under the mouse cursor, but when its an empty space (false only in perspective views) the coordinates are not correct?

**Comment by HuguesDelorme** [comment]
Hello Selahattin,

Function `GpxUtils::V3dView_to3dPosition()` is called only when picking attempt failed.
These "3D" mouse coordinates are computed in `MainWindow::onGuiDocumentAdded()`
```cpp
        auto selector = guiDoc->aisInteractiveContext()->MainSelector();
        selector->Pick(pos2d.x(), pos2d.y(), guiDoc->v3dView());
        const gp_Pnt pos3d =
                selector->NbPicked() > 0 ?
                    selector->PickedPoint(1) :
                    GpxUtils::V3dView_to3dPosition(guiDoc->v3dView(), pos2d.x(), pos2d.y());
        m_ui->label_ValuePosX->setText(QString::number(pos3d.X(), 'f', 3));
        m_ui->label_ValuePosY->setText(QString::number(pos3d.Y(), 'f', 3));
        m_ui->label_ValuePosZ->setText(QString::number(pos3d.Z(), 'f', 3));
    });
```

`V3dView_to3dPosition()` computes a 3D position by projecting the mouse position to a plane perpendicular to the actual view direction. See the coordinates with the "TOP" view for example(Z coord should be fixed).

**Comment by sbabadag** [comment]
Understand  thanks for the quick answer;
but is there a way that we can get the real coordinates in a ortho view?

**Comment by HuguesDelorme** [comment]
To do this I guess the user has to define a "privileged plane" and then mouse coordinates are computed inside that fixed plane.
For now it's useless in Mayo as it doesn't provide CAD commands like sketching, right ?

**Comment by sbabadag** [comment]
Thanks thats right.
