### ISSUE TITLE
Hot reload on file change

### ISSUE THREAD

**Issue by snapo** [fougue/mayo#153]
Would it be possible to add a Hot reload on a file change in the options?
My step files always change when i re-generate them, it would save me a few clicks every hour.
So if a filechange is detected for the currently open file, re-render it with the new file.

**Comment by HuguesDelorme** [comment]
![image](https://github.com/fougue/mayo/assets/939132/50f79d59-e61e-4f62-a71f-7714cc3de0a0)

See also this new option(`None` by default) to choose action on document file change:
![image](https://github.com/user-attachments/assets/29b72ad7-e3bf-41ff-98ff-97ac5951ab31)

**Comment by HuguesDelorme** [comment]
See also enhancement #279
