### ISSUE TITLE
Remove Qt dependency in `base` + `gui` + `graphics` modules

### ISSUE THREAD

**Issue by HuguesDelorme** [fougue/mayo#154]
There was some efforts in the past to remove usage of Qt in `base/` folder.
Qt dependency still remain only because of signals.
Complete removal of Qt by replacing signals with the [KDBindings](https://github.com/KDAB/KDBindings) library
It will make `base` and `io` modules easier to reuse as standalone libs

**Comment by Abde5** [comment]
Awesome! 👏👏👏
