### ISSUE TITLE
GLTF export coordinates converter

### ISSUE THREAD

**Issue by Daniel4144** [fougue/mayo#158]
Hi,

I imported a step file and exported it as gltf/glb and the resulting model is oriented wrong (tested in different viewers - Windows 3D viewer, Blender and in Unity imported with [glTFast](https://github.com/atteneder/glTFast).
I tested with the export setting Coordinates Converter which, as I understand, should result in different orientations, but the three options (Undefined, negZfwd_posYup, posYfwd_posZup) seem to make no difference.
I also tried to export as obj, which has the same setting, with the same result.

Am I doing something wrong or is the coordinate conversion not working?

**Comment by HuguesDelorme** [comment]
Hello @Daniel4144
Thanks for reporting this issue, sorry for the late response.
I've provided a fix in `develop` branch : glTF and OBJ writers now have parameters for input/output coordinate systems
Let me know if it fixes the issue on your side

**Comment by Daniel4144** [comment]
Thank you for looking into the issue @HuguesDelorme
Is there a build with the fix so I can check if it is fixed on my side?

**Comment by HuguesDelorme** [comment]
No unfortunately, not currently.
However I can generate one and give you a link to it.
What OS are you using ? Windows ?

**Comment by Daniel4144** [comment]
That would be great, I really appreciate your help.
I am using Windows 10

**Comment by HuguesDelorme** [comment]
Here it is:
https://www.fougue.pro/share/bin/mayo_v0.7.0.1043-77f594c_winx64_installer.exe
Let me know your feedbak

**Comment by Daniel4144** [comment]
I can confirm that this version works for me - now I am able to adjust the coordinate system, tested with both gltf and obj export.

Remark:
I don't see the benefit of having two parameters for the coordinate system. Maybe I am missing something, but isn't the input coordinate system always the same (the viewer always uses z up)?
Imo the default value for the input coordinate system should at least be posZup, in the test build you provided the default was undefined (and it crashed when I tried to restore default values).

**Comment by HuguesDelorme** [comment]
Thanks for your feedback.
I'm also doubtful about whether input coordinate system parameter is useful.
Example, here is a base part:
![image](https://user-images.githubusercontent.com/939132/201687990-f53d69e5-8112-40fc-a5d3-2d1ae0250b7c.png)

Export posZup -> posYup:
![image](https://user-images.githubusercontent.com/939132/201688195-501e3d1d-ce7b-4b67-b963-04a22e2aa2ff.png)

Export posYup -> posZup:
![image](https://user-images.githubusercontent.com/939132/201688335-d6459a7c-6bc6-499a-9676-e154d16fe9ce.png)

The input coordinate system parameter allows another transformation, but is it relevant ? I would say yes but not 100% sure
