### ISSUE TITLE
Caculate Volume or Stock Size

### ISSUE THREAD

**Issue by piggycatc** [fougue/mayo#175]
I wish I could calculate the volume. 

create boundig box(box, cylinder) -> calulating volume (stocksize)

select type
![123](https://user-images.githubusercontent.com/93959702/219288141-48dfe281-d905-473a-9438-d29875b893b0.PNG)

make bounding box -> offset
![234](https://user-images.githubusercontent.com/93959702/219288139-dccc2675-1415-4077-b7e6-38fbb2bf97cc.PNG)

calculate box volume
![345](https://user-images.githubusercontent.com/93959702/219288131-4a537bf0-cb0c-4483-a1ea-adf66ed61b1d.PNG)

**Comment by piggycatc** [comment]
I need a function to create a bounding box on the outside of an object and get its volume. please develop. please, please

**Comment by HuguesDelorme** [comment]
Duplicates #252
