### ISSUE TITLE
QToolBar

### ISSUE THREAD

**Issue by thyis** [fougue/mayo#176]
Dear contributor could you please add some toolbar modeling?
    best wish!

**Comment by HuguesDelorme** [comment]
Can you elaborate on what you would like for this feature?

**Comment by thyis** [comment]
Some toolbars  contain one action two button  body selected for Boolean, like UG plugin in toolbars.

**Comment by HuguesDelorme** [comment]
Actually you would like some modeling features(primitives, fillet, chamfer, bore, ...) to be supported?

**Comment by thyis** [comment]
Year,  could you give me a modeling feature app? By the way ,when I click the model tree 'Delete button' with the mouse, I lose other model tree nodes.
