### ISSUE TITLE
surpport  build a cube?

### ISSUE THREAD

**Issue by thyis** [fougue/mayo#181]
may  i  build a  cube in mayo?   Expect your reply.

**Comment by HuguesDelorme** [comment]
Hello no you can't, Mayo is a pure 3D CAD viewer/converter application
But having some CAD modelling features would be great, through scripting

**Comment by HuguesDelorme** [comment]
You can extend Mayo by code though, see discussion https://github.com/fougue/mayo/discussions/81

**Comment by thyis** [comment]
THANKS A LOT
