### ISSUE TITLE
Command-line converter: folder with multiple input files

### ISSUE THREAD

**Issue by yvanblanchard** [fougue/mayo#183]
Hello,
Is it possible to process multiple input files for conversion using the CLI, selecting a folder path. Since I have hundreds of files to convert at once.
Of course, I can do a loop in a script, but was wondering if a more efficient way could be done.

Thank you

**Comment by HuguesDelorme** [comment]
Yes on Windows, to process the direct files contained in a folder, this command line can be used:
`for %f in ("d:\data\*.stp") do (mayo.exe --no-progress "%f" --export "%~dpnf.gltf")`

This will convert STEP files contained in `D:\data` folder to glTF format, keeping the same base name.

I like the fact Mayo CLI works only on single input file. It keeps the command line processing simple and "automation" is up to the user. But it appears the console output is garbled when working sequentially on multiple files(not tested with Unix-like sh though)
This needs to be adressed

**Comment by yvanblanchard** [comment]
Thank you Hugues.
