### ISSUE TITLE
Help! Files can be opened,but do not show 

### ISSUE THREAD

**Issue by HonorableLeon** [fougue/mayo#197]
Hi my friend!Thanks for your codes!
We are building the project with **Microsoft Visual C++ 2019** + **OpenCASCADE-7.7.0-vc14-64** + **Qt 5.15.2** in Windows 10,after some times trying,we succeed and the program runs.
However，when we open files,the programe shows nothing.
So,can you help?
![image](https://github.com/fougue/mayo/assets/93172976/680000d8-0ab0-4cb2-8f77-eb5fa23ea3ae)

**Comment by HuguesDelorme** [comment]
Hello @HonorableLeon
Are you using prebuilt Qt 5.15.2 binaries or did you build it yourself?
There are no icons in your screenshot, Mayo icons are in svg format and require `Qt5Svg.dll` + plugins `qsvgicon.dll` and `qsvg.dll`
So check you have those DLLs and they are accessible to Mayo exe

Also it's worth trying to download and install Mayo 0.7.0 to check it works on your system, see https://github.com/fougue/mayo/releases/tag/v0.7.0

**Comment by HonorableLeon** [comment]
Thanks for your answer@HuguesDelorme 
I'm using the prebuilt Qt 5.15.2 binaries,these dlls are copied in the same folder with Mayo exe,but the programe shows blank ,same with yesterday.
Mayo 0.7.0 was working on my system.

**Comment by HonorableLeon** [comment]
Solved!Works!Thank you my friend @HuguesDelorme 
![image](https://github.com/fougue/mayo/assets/93172976/a89992b2-8f4d-4b8f-85bb-af9b362bb314)
My settings:
![image](https://github.com/fougue/mayo/assets/93172976/a8dddc60-db9b-4c77-a4d6-d4cfdb1cae1e)
