### ISSUE TITLE
Measurements

### ISSUE THREAD

**Issue by leoheck** [fougue/mayo#202]
Hi, I just found this nice tool, I am looking to see if it can be used to measure some features of my model.
For instance, is it possible to measure the center of a circle to another point/edge/line?

**Comment by HuguesDelorme** [comment]
Hello @leoheck 
You can try this new measurement tool introduced by @neuoy called "center-to-center distance"
Example of the distance between the center of a circle and a point:
![image](https://github.com/fougue/mayo/assets/939132/75882fd0-5dae-46d5-a717-8b3844f9e63c)

Notice that this feature isn't shipped in v0.7.0 but is available in the `develop` branch so you will have to build Mayo from source code to use it.
See #195

**Comment by leoheck** [comment]
The name is a bit misleading, I guess. But the feature is promising, thank you for sharing this.
