### ISSUE TITLE
color face

### ISSUE THREAD

**Issue by thyis** [fougue/mayo#203]
Hello, sir.
When I colored a face of the imported stp, it didn't work.  Export and re-import the colored stp, the whole stp color is OK but the face not.  What should I do to color the face?    both gfxScene->redraw();  and gfxScene->addrObject();   didn't work.
Looking forward to your reply.

**Comment by HuguesDelorme** [comment]
Hello @thyis 
It's hard to help you precisely without knowing what you did
Is there a branch/commits where I can see your changes?

**Comment by thyis** [comment]
Thanks.  the face of .stp has been successfully colored, but not the edge.
![image](https://github.com/fougue/mayo/assets/63134171/ec22edb2-ff9e-4236-a617-18beadb44007)

**Comment by HuguesDelorme** [comment]
You probably need to create an XDE subshape for the edge to be colored and set the color with:
`doc->xcaf().colorTool()->SetColor(edgeLabel, color, XCAFDoc_ColorCurv);`

**Comment by thyis** [comment]
it didn't work, like this:
if (gfxShape.ShapeType() == TopAbs_ShapeEnum::TopAbs_EDGE)
				{
					TDF_Label gfxlabel = shapeTool->FindMainShape(gfxShape);
					TDF_Label colorEdge = doc->xcaf().shapeTool()->AddSubShape(gfxlabel, TopoDS::Edge(gfxShape));
					doc->xcaf().colorTool()->SetColor(colorEdge, color, XCAFDoc_ColorCurv);
				}

**Comment by thyis** [comment]
Thanks.   it work.
![image](https://github.com/fougue/mayo/assets/63134171/ee1fe726-1c24-4881-ac37-05b15bcec2fa)

**Comment by thyis** [comment]
How it find the unique identification of the edge, such as a number of integer. Like Unigraphics NX, every point, edge, line, and surface has a six-digit ID,

**Comment by thyis** [comment]
Dear  sir,
it surprised change "object->Attributes()->SetFaceBoundaryDraw(false)" to  make edge coloring work.
I want to give each edge or face unique ID,  but  it failed,

**Comment by HuguesDelorme** [comment]
What is not working about topology unique ID?
I mean what is the problem with the code you mentionned above?
