### ISSUE TITLE
explode assemble  question

### ISSUE THREAD

**Issue by thyis** [fougue/mayo#204]
Dear Sir,

1.when it explode assemble at 50%,   
2.export it, 
3. import it,
 it cannot save exploding assemble at 50% status,    what   can  i export  the explode assemble at 50%,   

![image](https://github.com/fougue/mayo/assets/63134171/1478f98e-a526-49a3-b725-2bbe8cf48060)

**Comment by HuguesDelorme** [comment]
Hello @thyis
The explode feature works on the transformation matrix of the 3D graphics and not on topology entities as you expect
This feature is intended for visualization purposes, not to change the model
