### ISSUE TITLE
Smaller obj file size?

### ISSUE THREAD

**Issue by swall-pxc** [fougue/mayo#205]
# Some Background info:
- I use the cli in order to convert stp files to obj files in a pipeline.
- Later I want to ship the resulting obj files in a Web App.
- I would like to have about 10x smaller files (to speed up loading etc.)
- I am fine with worse quality

# Questions:
- Is there some parameter to reduce the file size (lowering the quality)?
- Is there something in the source code to change that at build time?

**Comment by HuguesDelorme** [comment]
Hello @swall-pxc 
Have a look at the "BRep Meshing" parameters in Tools->Options dialog:
![image](https://github.com/fougue/mayo/assets/939132/39ee3946-ee14-4c1a-8b7f-61e196a841ac)

Try to downgrade the mesh quality from "Normal" to "Coarse" or "Very Coarse"
Once you find the values that meet your needs then export the settings with:
![image](https://github.com/fougue/mayo/assets/939132/d13387ed-0723-4a8c-8a2c-ee696040cf31)

You will get an INI file that you can pass to mayo CLI:
`$> mayo.exe D:\Data\inputfile.step --settings myoptions.ini --export outputfile.obj`

You can edit the INI file in a text editor and change the values directly, name of the relevant parameter is `meshingQuality`

**Comment by HuguesDelorme** [comment]
@swall-pxc 
See also related issue #126

**Comment by swall-pxc** [comment]
Thank you
