### ISSUE TITLE
Keep it exploding

### ISSUE THREAD

**Issue by thyis** [fougue/mayo#209]
I do not Keep it exploding at 49%   when i export  the exploding assemblies ,"explode assemblies" widget option, how does Keep it exploding?
![image](https://github.com/fougue/mayo/assets/63134171/2b542690-349c-45bb-8bf6-716a31b7f5f3)

**Comment by HuguesDelorme** [comment]
Hello @thyis 
This question was already answered here https://github.com/fougue/mayo/issues/204#issuecomment-1619629887

**Comment by thyis** [comment]
Thanks ,  i  see.
how to change the model   in mayo.

**Comment by HuguesDelorme** [comment]
You need to change the location of each instance(also named reference) in the assembly
Have a look at `XCAFDoc_ShapeTool::SetLocation()`

**Comment by thyis** [comment]
very  thanks
