### ISSUE TITLE
Help！After modified the .ui file,new built Mayo will not start up anymore

### ISSUE THREAD

**Issue by HonorableLeon** [fougue/mayo#212]
Hi my friend @HuguesDelorme ,We are building the project with Microsoft Visual C++ 2019 + OpenCASCADE-7.7.0-vc14-64 + Qt 5.15.2 in Windows 10,we have some problems when we start up Mayo after modified the .ui file. What makes it worse is that we can not start up Mayo any more,no matter it is a Older one,which worked yesterday!

**Comment by HuguesDelorme** [comment]
Hello, is it crashing at startup?
In a terminal, run `git stash` in your Mayo checkout. This will save all your changes in some "draft" commit and make your checkout "clean"
Then build again, if Mayo is back you can run `git stash apply` to retrieve your changes
