### ISSUE TITLE
getShape is null

### ISSUE THREAD

**Issue by thyis** [fougue/mayo#213]
Hello：
Dear sir:
when  i pick the ais1_oc_214.stp,  move once is ok,
TopoDS_Shape gfxShape = getShape(gfxOwner);
TDF_Label gfxLabel = doc->xcaf().findShapeLabel(gfxShape);
shapeTool->SetLocation(gfxLabel, loc, theRefLabel);  
move twice getShape  is null  ,what happened.
![image](https://github.com/fougue/mayo/assets/63134171/513d56cd-7b99-4a9f-b240-771ec218a7e6)

**Comment by HuguesDelorme** [comment]
Hello, it's hard to give you some clues about your issue.
Seems like the graphics owner is no longer valid after the shape move.
Is the code of `getShape()` the same as in `measure/measure_tool_brep.cpp` at L104?

**Comment by thyis** [comment]
yes  the code of getShape()  is the same as in measure/measure_tool_brep.cpp at L104

**Comment by thyis** [comment]
Is it possible that it is caused by the assembly relationship， instance label？

**Comment by thyis** [comment]
How to update synchronously  owner been modified shape?
