### ISSUE TITLE
export  then import  location  make reference

### ISSUE THREAD

**Issue by thyis** [fougue/mayo#214]
Hello,
when  i  choose  a shell  moving ,  
1.export it , 
2. import it,
3. it could changes location,  but creates reference with location to it,
![image](https://github.com/fougue/mayo/assets/63134171/ca1e581a-1ad7-4a0b-aff3-29f0535c3c20)
![image](https://github.com/fougue/mayo/assets/63134171/0ad9f6b6-ddf1-44ff-874f-cc082d324673)

**Comment by HuguesDelorme** [comment]
Hello @thyis
I'm pleased to help you with your software derived from Mayo
But the "Issues" pages are dedicated to Mayo itself, reporting your issues specific to your software might confuse Mayo users
Please create a new thread in the "Discussions" place. I suggest the "Show and tell" category(see https://github.com/fougue/mayo/discussions/categories/show-and-tell)
In the meanwhile I'm going to close that issue, see you in the Discussions soon!

**Comment by thyis** [comment]
i am so sorry for the mayo user.
