### ISSUE TITLE
a couple build and run time error

### ISSUE THREAD

**Issue by easternbun** [fougue/mayo#219]
Okay the last open folder property is causing the error, but I am at lost of why and how to fix it. 
it seems that path string has invalid characters I assume chinese characters
what is more is why is it trying to open wechat chat folder when it has nothing to do with mayo.
what is more is mayo's qapplication is trying to run ros2_foxy which is a robotic system 
![image](https://github.com/fougue/mayo/assets/42531982/92636e3d-8ad8-422c-8058-79fee90f8d75)
![image](https://github.com/fougue/mayo/assets/42531982/715b9cd3-8f96-4fdb-a9f0-3c73c652b18a)
![image](https://github.com/fougue/mayo/assets/42531982/d879b411-c1c9-4d6f-81c3-ec742459ba5f)

================

So I redownload the mayo and found a build error and a run time error

I followed the instructions given by Build-instructions-for-Windows-MSVC
the QT version is 6.4.3 with msvc2019-64bits
the OCC version is 7.6.0
the cl.exe is  From "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\Hostx86\x64\"
( Note cl is strange because first time I build with qmake on .pro file it did not throw a "cl could not be found" error, so I choose a latest version of cl I could find, which is from above directory. )

======

**the build error:**
GL_GLEXT_VERSION is redefined
The code line at 268 of command_system_information.cpp says QString cannot be converted to QChar

**the run error:**
memory error at run time when loading appModule settings

![image](https://github.com/fougue/mayo/assets/42531982/484738ea-d838-4c9f-b32e-f3efae1adcfe)
![image](https://github.com/fougue/mayo/assets/42531982/ee1a208b-9e23-42b8-9c89-1fb00a8ae688)
![image](https://github.com/fougue/mayo/assets/42531982/6ffdeb2f-ee59-4ef5-aea0-57ca8b859897)
![image](https://github.com/fougue/mayo/assets/42531982/58f8b6a6-d0c2-4ded-9c80-4a1614d8f84a)

my Install output
![image](https://github.com/fougue/mayo/assets/42531982/55527f9a-4e41-4aec-ac38-1b1ff993a47a)

**Comment by HuguesDelorme** [comment]
Hello @easternbun
Thanks for your feedback!

I've just pushed a fix in develop branch for the compiler error you reported(in command_system_information.cpp). This one happened for Qt6 and not Qt5. It reminds me to check compilation against Qt6 in the CI(ie GitHub Actions)

The one about GL_GLEXT_VERSION is a compiler warning(doesn't prevent compilation to succeed) and there's no fix I can find. This happens with OpenCascade 7.6.0 and with 7.7.0 version. You can ignore this warning, if it's really issue then try to update to OpenCascade 7.7.0

About the crash with Variant::toConstRefString() that one is weird. I suggest to clear the contents of the lastOpenDir setting in the registry and try again. Does the crash happens on the std::get<std::string>() or after with the creation of the FilePath object?
Would be great to see the callstack and paste here also what's inside the variant object as seen by Visual Studio(Code)

**Comment by easternbun** [comment]
> 

@HuguesDelorme

Thanks for the reply! 
The crash happened at line 139 of settings.cpp "d->loadPropertyFrom" when trying to load lastOpenFolder property, and in the function loadPropertyFrom(), the program crashed at fromVariant(property, value). 
![image](https://github.com/fougue/mayo/assets/42531982/3e378d06-a367-4707-b3e9-6e55cde4fa38)
![image](https://github.com/fougue/mayo/assets/42531982/ee37de0a-3d8f-4c21-a417-d9e71ae85f03)

**Comment by zerger** [comment]
i think maybe the path is contain chinese or  deleted

**Comment by zerger** [comment]
![Snipaste_2023-11-01_09-31-02](https://github.com/fougue/mayo/assets/741263/e498c4dd-2351-43ed-920d-42ddba879dea)
![Snipaste_2023-11-01_09-32-59](https://github.com/fougue/mayo/assets/741263/00365ef0-3127-4aa8-976b-c3bfe2dc34ed)

**Comment by zerger** [comment]
![Snipaste_2023-11-01_09-36-00](https://github.com/fougue/mayo/assets/741263/a4d9907a-c941-4ed2-9003-d910eb70583a)

**Comment by HuguesDelorme** [comment]
Hello @zerger
Thanks for the elaborated feedback
I've just pushed a fix for this issue on `develop` branch, can you please check if it's solved on your side?

**Comment by HuguesDelorme** [comment]
Fixed with commit c2c1147
