### ISSUE TITLE
cannot display .ply model exported from agisoft --win10

### ISSUE THREAD

**Issue by Wangpeiyu** [fougue/mayo#223]
Thank you for sharing such a great work. It's really amazing.But I encountered a problem during use Mayo,cannot display( .ply, obj format ) 3d model and ply format point cloud data exported from agisoft.

But,i can see thumbnail image of the loaded data in the welcome page.
![image](https://github.com/fougue/mayo/assets/7277811/7412c43d-7a9d-4e81-8e20-c7a32b3a4724)

nothing in main page:
![image](https://github.com/fougue/mayo/assets/7277811/49bfa1d2-b5af-4540-944e-10f70d282188)

app version:mayo_v0.7.0.1113-f88a35d_winx64_installer.exe
os version:Windows 10 pro 22H2 19045.3324

sample data:
https://drive.google.com/file/d/1v9NyhWnLeJ9k85ILX8fq9GMfuWvC60d3/view?usp=drive_link

**Comment by HuguesDelorme** [comment]
Hello @Wangpeiyu
The provided PLY model is far from the origin and as the origin trihedron graphics are taken into account for the "fit all in view" then the model is nearly invisible
Hide the origin trihedron graphics by unchecking menu _Display->Show Origin Trihedron_:
![image](https://github.com/fougue/mayo/assets/939132/52bedb20-836f-448c-8d4b-1394b3de7c82)
And then click on the "Fit All" button under the 3D view cube
See also issue #76

**Comment by Wangpeiyu** [comment]
Thank you very much for your reply. It has solved a major problem for me.
