### ISSUE TITLE
How to solve the problem of importing step

### ISSUE THREAD

**Issue by thyis** [fougue/mayo#229]
Dear sir, 
When I delete the document,   it done.
![image](https://github.com/fougue/mayo/assets/63134171/d450e6be-2715-4cde-8770-1894d052e55c)
then select it to export,  it  done.
![image](https://github.com/fougue/mayo/assets/63134171/5b54cc25-c8d0-406c-ba7b-dd806070f6a2)
Finally, insert the exported document,  the graphics are not deleted but  position has changed.  how  to  solve , it should be an empty graph.
![image](https://github.com/fougue/mayo/assets/63134171/5b4efac3-b909-4cbd-bbfa-d54065d73e87)

**Comment by thyis** [comment]
Hello, Dear Sir,
I have come to a solution that seemingly works: 
        TDF_Label shapeLabel = m_xcaf.shapeTool()->FindShape(m_xcaf.shapeTool()->GetShape(entityLabel));
	m_xcaf.shapeTool()->RemoveComponent(entityLabel);
	m_xcaf.shapeTool()->RemoveShape(shapeLabel);
        entityLabel.ForgetAllAttributes();
	entityLabel.Nullify();
	m_xcaf.shapeTool()->UpdateAssemblies();
Is this a valid solution? Do I need to do some cleanup to the document so it does not lead to some undefined behavior?

**Comment by HuguesDelorme** [comment]
Thanks @thyis for your proposal
I will make some tests and merge the patch into the develop branch
At first sight I'm not sure if this is needed:
````c++
shapeLabel = shapeTool->FindShape(shapeTool->GetShape(entityLabel));
shapeTool->RemoveShape(shapeLabel);
````
Isn't the call to `shapeTool->RemoveComponent(entityLabel)` sufficient?

**Comment by thyis** [comment]
Sometimes I just need to remove one of the components， ignore  "shapeTool->RemoveShape(shapeLabel)"，it it faild remove  shape.
