### ISSUE TITLE
About location of assembly parts 

### ISSUE THREAD

**Issue by Alonewolf05** [fougue/mayo#233]
Hello dear developers,

I imported a PCB STEP model I designed. As you can see from the image below, parts are not where it is supposed to be.

![image](https://github.com/fougue/mayo/assets/42738816/d547e1be-464b-4bd0-a83e-50a184e7b572)

In xcaf.cpp file, when I enabled #if part in the code below

    TreeNodeId XCaf::deepBuildAssemblyTree(TreeNodeId parentNode, const TDF_Label& label)
    {
    Expects(m_modelTree != nullptr);

    const TreeNodeId node = m_modelTree->appendChild(parentNode, label);
    if (XCaf::isShapeAssembly(label)) 
    {
        for (const TDF_Label& child : XCaf::shapeComponents(label))
            this->deepBuildAssemblyTree(node, child);
    }
    else if (XCaf::isShapeReference(label))
    {
        const TDF_Label referred = XCaf::shapeReferred(label);
        this->deepBuildAssemblyTree(node, referred);
    }
    #if 0 -> 1
    else if (XCaf::isShapeSimple(label)) 
    {
        for (const TDF_Label& child : XCaf::shapeSubs(label))
            this->deepBuildAssemblyTree(node, child);
    }

    #endif

    return node;

assembly becomes the image below. Location of parts are correct but upper and lower faces are gone. 
And the software starts to consume more RAM. I assume it is about selection and model tree mechanisms. Not important right now.

![image](https://github.com/fougue/mayo/assets/42738816/311fbbde-e703-4085-bc5b-6bbf8c4723a0)

My question is how I can transform the location of parts without adding subshapes into assembly tree. Should I use `XCAFDoc_ShapeTool::SetLocation()` ? If so, where can I get the location data before running `XCAFDoc_ShapeTool::SetLocation()` function?

I attached the model here. POV. I know it is a silly PCB I am learning :)

[powerbank_IP5306_v5.zip](https://github.com/fougue/mayo/files/13184473/powerbank_IP5306_v5.zip)

**Comment by HuguesDelorme** [comment]
Fixed with 84cb80a in `develop` branch:
![image](https://github.com/fougue/mayo/assets/939132/dadc8af6-e80a-4b64-b88c-167f16500c62)

Beware that all LED, C and R can't be considered as "instanciated" parts because the COMPOUND reference shape uselessly redefines the color(white).
