### ISSUE TITLE
NEW BEE REQUEST

### ISSUE THREAD

**Issue by chandrasekhar574** [fougue/mayo#24]
Please upload any video ,process for this project to be  integration with opencascade7.4..please understand my situation as iam new bee to coding

steps i done
1.Install and able to built open cascade with vs2017 without any issues

**Comment by HuguesDelorme** [comment]
You don't need to build OpenCascade. Pre-built DLLs can be installed with this setup here :
    https://www.opencascade.com/content/latest-release

Feel free to post questions here about any further problem.

**Comment by chandrasekhar574** [comment]
Hi All,

How to build mayo  application/project?.please show me any way to use your code.i tried to use read.md text file however i didn't get anything.kinsly help me

Kind regards,
Chandrasekhar.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by HuguesDelorme** [comment]
Here are some steps :

1. Download and install OpenCascade https://www.opencascade.com/content/latest-release
2. Download and install Qt5(make sure during the installation you choose vs2017 DLLs) https://www.qt.io/download-thank-you?os=windows&hsLang=en
3. Open Visual C++ 2017 x64(native) command line interpreter(have a look in your Start Menu)
4. Set Qt5 environment "set PATH=YOUR_QT5DIR\bin;%PATH%"
5. Set OpenCascade environment "call YOUR_OCCDIR\env.bat"
6. Clone Mayo repository somewhere "git clone https://github.com/fougue/mayo.git"
7. cd mayo;  mkdir build;  cd build
8. qmake ..\mayo.pro
9. nmake

**Comment by chandrasekhar574** [comment]
I will try this and give you feedback.thanks for your effort to write me back.

Regards,
Chandrasekhar.
________________________________
