### ISSUE TITLE
Provide Mayo binaries as Windows ZIP archive

### ISSUE THREAD

**Issue by git-tiger** [fougue/mayo#244]
Is there option to run the viewer without installing. My company does not allow installation of software.

**Comment by HuguesDelorme** [comment]
Work has to be done for a WebAssembly port. So it will be possible to safely run Mayo with eg wasmer

**Comment by HuguesDelorme** [comment]
@git-tiger 
Do you mean having instead a ZIP archive of the binaries you can extract somewhere and directly run `mayo.exe`?

**Comment by git-tiger** [comment]
Yes, no need to install.

**Comment by HuguesDelorme** [comment]
Version 0.8.0 will be shipped this week, I will try to provide a ready-to-use ZIP archive containing the binaries

**Comment by HuguesDelorme** [comment]
Choose `Mayo-0.8.0-win64-binaries.zip` in the [Releases](https://github.com/fougue/mayo/releases/tag/v0.8.0) page

**Comment by git-tiger** [comment]
Unfortunately, it flagged as Reputation virus, and quarantined the mayo.exe file.
Office computer is using Symantec Antivirus.

**Comment by HuguesDelorme** [comment]
Mayo binaries were analyzed by up-to-date avast anti-virus and no infection was reported.
Might probably be a Symantec false-positive and right now there's nothing I can do to workaround this.
In the future I will sign Mayo binaries with an official certificate, that should solve the issue.
