### ISSUE TITLE
How to fix the running error?

### ISSUE THREAD

**Issue by softempire** [fougue/mayo#25]
![image](https://user-images.githubusercontent.com/1004480/95458027-3d242e80-09a4-11eb-824f-d488a6fd525c.png)

**Comment by HuguesDelorme** [comment]
What is your build environment ?
Qt version ?
OpenCascade version ? Did you install pre-built binaries from OpenCascade Download Center ?

If the problem persists try to load mayo.exe in Dependency Walker utility (make sure to Qt and OpenCascade DLLs can be found)

**Comment by softempire** [comment]
I'm using OpenCascade OpenCASCADE-7.4.0-vc14-64, and Visual studio is 2019
Qt is 5.13.1

**Comment by softempire** [comment]
![image](https://user-images.githubusercontent.com/1004480/95472895-238be280-09b6-11eb-8cc9-71c239cca8e3.png)

**Comment by softempire** [comment]
I'm using the command line. I launched a Visual Studio dev console and then QMake and then nmake

**Comment by HuguesDelorme** [comment]
OK try to update your git clone with latest changes from origin/develop
I know there is a broken commit with missing *.qm files referenced in mayo.qrc
Maybe you are experiencing this

**Comment by softempire** [comment]
> OK try to update your git clone with latest changes from origin/develop
> I know there is a broken commit with missing *.qm files referenced in mayo.qrc
> Maybe you are experiencing this

Thank you, I'll try this.

**Comment by HuguesDelorme** [comment]
Are you using pre-built Qt binaries ? For which VisualStudio version ?

**Comment by HuguesDelorme** [comment]
Hello @softempire
Did you solve this issue ?
