### ISSUE TITLE
Some OFF files fail to open

### ISSUE THREAD

**Issue by mmuman** [fougue/mayo#258]
I recently fixed OFF import in OpenSCAD, and it seems [some files around](https://people.sc.fsu.edu/~jburkardt/data/off/off.html) interpret the specs a bit loosely. Some of the samples mentioned for example put the number of vertices/faces on the same line as the "OFF" header.

**Comment by HuguesDelorme** [comment]
Can you provide some OFF files that fail to open in Mayo?

**Comment by mmuman** [comment]
> Can you provide some OFF files that fail to open in Mayo?

Some of those linked to in the first post.

At least `socket.off` there.
