### ISSUE TITLE
Only cli usage

### ISSUE THREAD

**Issue by Spoutnik97** [fougue/mayo#260]
Hi, thanks for your work, and the documentation!
Do you have advices to make a light version of your app without GUI ? I would like to use it in a docker container, so the lightest version is the best

**Comment by HuguesDelorme** [comment]
So you would like to only use the converter from command-line?
Ideally without any Qt dependency?
Or at least just QtCore module(on Ubuntu that would be the [libqt5core](https://packages.ubuntu.com/jammy/libqt5core5a) package for example)

**Comment by Spoutnik97** [comment]
Yes exactly

I would like to have the lightest docker image to convert files from an api

**Comment by HuguesDelorme** [comment]
Hello @Spoutnik97
I've made Mayo GUI and CLI distinct application in develop branch
See new respective CMake options `Mayo_BuildApp` and `Mayo_BuildConvCli`(both ON by default)
The batch converter is now a distinct exe(`mayo-conv.exe` on Windows) and it links to the same OpenCascade runtime DLLs as the GUI app, but for Qt only QtCore is linked to(no QtGui, QtWidgets, QtOpenGL and QtSvg)
