### ISSUE TITLE
Installation forces restart of computer without confirmation!

### ISSUE THREAD

**Issue by iyiarz** [fougue/mayo#265]
I think this is related to the Visual Studio element of the installation. All my apps started closing and I was lucky not to loose anything important.

**Comment by HuguesDelorme** [comment]
Sorry about that, the InnoSetup installer embeds the Visual C++ redistributable component which is launched at last step, to install Visual C++ runtime DLLs
For the next coming version I will remove it from the installer and instead explicitly deploy needed Visual C++ runtime DLLs

**Comment by HuguesDelorme** [comment]
Duplicates #266
