### ISSUE TITLE
Silent auto reload (#279) reloads the model twice

### ISSUE THREAD

**Issue by Jopie01** [fougue/mayo#284]
I wanted to comment on issue #279 but I was to late ... the feature was just implemented. So I pulled the repo and build Mayo and tried it out.

What I discovered was that the model is reloaded twice. in the tasks window there are also two progress bars.

![Screenshot_20240730_115939](https://github.com/user-attachments/assets/20c5627d-e0fc-4ec4-96ac-5796975493dd)

**Comment by HuguesDelorme** [comment]
Question: what is your OS?

**Comment by Jopie01** [comment]
| Question: what is your OS?

OS: Fedora 39
Platform: x86_64
Desktop: KDE

**Comment by Jopie01** [comment]
I just noticed that the 3D model is loaded twice. So two exact models are laying on top of each other. Both have also the exact same name. That explains the double reloading.

To reproduce:
- build Mayo from the latest source
- start Mayo and open a STEP file
- in another program make some changes and export to a STEP file and overwrite the opened STEP file in Mayo
- Mayo will detect that the file has changed and start reloading

What you can notice is that on the first reload, the opened file is closed, but then the file is opened twice.
