### ISSUE TITLE
Capping hatch scale is too small

### ISSUE THREAD

**Issue by Jopie01** [fougue/mayo#285]
I've build Mayo myself and after clipping a model I see a complete black plane. I've also compared it with version 0.8.0 which I downloaded as AppImage. Below you can see the differences.

Development version I builded myself:
![Screenshot_20240730_120728](https://github.com/user-attachments/assets/1192cbe0-ad00-4082-acda-ef225474d354)

Version 0.8.0-x86_64.AppImage:
![Screenshot_20240730_120901](https://github.com/user-attachments/assets/239f5d08-3af6-42c8-a0bd-48435f85fa33)

As you can see the light is different and the hatching is completely black. Has this something to do with OCC?

OS: Fedora 39
Platform: x86_64

**Comment by HuguesDelorme** [comment]
Can you check your options in Mayo?
![image](https://github.com/user-attachments/assets/d7faf26f-b02f-47d0-87b6-39437a416c39)

**Comment by HuguesDelorme** [comment]
Please give also the OpenCasccade version you use to build Mayo

**Comment by Jopie01** [comment]
I have also both 'Capping' and 'Capping Hatch' checked. If I uncheck the 'Capping Hatch' the colors are back.

> Please give also the OpenCasccade version you use to build Mayo

I followed the build instructions for Linux on https://github.com/fougue/mayo/wiki/Build-instructions-for-Linux and specifically Fedora. I have the following opencascade packages installed:
```
opencascade-foundation-7.6.3-4.fc39.x86_64
opencascade-modeling-7.6.3-4.fc39.x86_64
opencascade-ocaf-7.6.3-4.fc39.x86_64
opencascade-visualization-7.6.3-4.fc39.x86_64
opencascade-draw-7.6.3-4.fc39.x86_64
opencascade-devel-7.6.3-4.fc39.x86_64
```

**Comment by HuguesDelorme** [comment]
Mayo AppImage is built with OpenCascade 7.7.0
Right now I have no idea what is causing the bug you reported. If you zoom in, do you see the capping hatch at some point?
I will have to install fedora, build mayo and try to reproduce the problem

**Comment by Jopie01** [comment]
> Mayo AppImage is built with OpenCascade 7.7.0

Is it possible to build a new AppImage with the latest changes? Maybe there has been a change in a occ version between 7.6 and 7.7 which is causing this.

**Comment by HuguesDelorme** [comment]
Latest Mayo is working fine on Ubuntu 20.04 with OpenCascade 7.7
![image](https://github.com/user-attachments/assets/98266791-f068-4260-a8e7-6c2fc7a95bf7)

AppImages are produced only with new release, right now there's no CI to automatically produce Mayo AppImages
Maybe you can try with latest OpenCascade(it will need to be built)

**Comment by Jopie01** [comment]
Well then I think it's because of an old version of opencascade. 

>  I will have to install fedora, build mayo and try to reproduce the problem

You have to install Fedora rawhide which comes with version 7.8. Before rawhide there is 7.6. Building opencascade from source is going to be a real pain. I will spin up a new VM with Fedora rawhide and see what it brings.

**Comment by Jopie01** [comment]
I created a new VM and installed Fedora rawhide nightly from https://openqa.fedoraproject.org/nightlies.html. I choose the KDE Live iso and installed that. Then I followed the build instructions for building Mayo. In this case opencascade version 7.8 was used.

But the problem still exists 😢 .

**Comment by HuguesDelorme** [comment]
Bad news, one thing that can be tested is to check clipping features in OpenCascade Draw(TCL) environment
This will help figure out if the issue is on Mayo or OpenCascade side

**Comment by Jopie01** [comment]
The weird thing to me is that it fails on Fedora, but Ubuntu is fine. I don't know when a new release will be made, but I'm very interested to see what the AppImage of that release does. Maybe there is even a opencascade dependency which is failing etc. So I'm going to wait for the new release before testing and digging deeper.

**Comment by HuguesDelorme** [comment]
You can try this and check hatched clipping planes are working in OpenCascade:
1. Open a terminal
2. cd in `OpenCascade/samples/tcl` folder
3. Run `DRAWEXE` located in your OpenCascade `bin` folder(eg OpenCascade/bin/DRAWEXE)
4. Type `source dimensions.tcl`

If you get an error about unknown `locate_data_file` command then edit file `samples/tcl/dimensions.tcl` and replace those lines accordingly(make sure to use correct paths of course):
````tcl
set aTopLoc [locate_data_file occ/Top.brep]
set aBotLoc [locate_data_file occ/Bottom.brep]
set aHatch  [locate_data_file images/hatch_1.png]
````
eg:
````tcl
set aTopLoc /opt/libs/opencascade-7.7.0/data/occ/Top.brep
set aBotLoc /opt/libs/libs/opencascade-7.7.0/data/occ/Bottom.brep
set aHatch  /opt/libs/libs/opencascade-7.7.0/data/images/hatch_1.png
````

**Comment by Jopie01** [comment]
OK, problem is with Opencascade and I think with the RPM packages in Fedora. When I execute the commands, I get a 3D window with the clipped part with dimensions. But the hatching is completely black. What I noticed on the console was:

```
Error: no image library available
Error: no image library available
```
So I looked at the system information which showed the OCCT build configuration:
```
Open CASCADE Technology 7.6.3
Tk enabled (HAVE_TK)
Xlib enabled (HAVE_XLIB)
TBB enabled (HAVE_TBB)
FreeType enabled (HAVE_FREETYPE)
FreeImage disabled
FFmpeg disabled
OpenGL: enabled (HAVE_OPENGL_EXT)
OpenVR disabled
RapidJSON disabled
Draco disabled
VTK enabled (HAVE_VTK)
Exceptions enabled
Compiler: GCC 13.1.1
Architecture: AMD64
OS: Linux
```
It's clearly a problem in how Opencascade is build for Fedora.

**Comment by HuguesDelorme** [comment]
Well spotted!
FreeImage was disabled when building OpenCascade RPM packages
Capping hatch uses a texture so it needs to load image files through FreeImage library
