### ISSUE TITLE
Enhance "Fit All" and add "Fit selected"

### ISSUE THREAD

**Issue by Mannshoch** [fougue/mayo#292]
I exported a part from a file into an other. "Fit all" does not focus on this file. I assume that beside the bodies for "fit all" the origin is also used.
Please do not use Origin for fit all if one or more bodies are inside the file.

I miss also a fit selected to see selected bodies fit into the view.

**Comment by HuguesDelorme** [comment]
The "Fit all" issue you reported is probably linked to this one:
https://github.com/fougue/mayo/issues/76
