### ISSUE TITLE
The resource file is error in qt project file

### ISSUE THREAD

**Issue by tony80437** [fougue/mayo#298]
the resource file is Qt project is :
RESOURCES += $$MAYO_DIR/mayo.qrc

but it does not exists, it may be 
RESOURCES += $$MAYO_DIR/images/mayo.qrc

**Comment by HuguesDelorme** [comment]
Thanks for reporting this issue
You should use CMake to build Mayo(see `CMakeLists.txt` file at project root folder)

**Comment by HuguesDelorme** [comment]
Removed `scripts/qmake` folder, CMake is the build system to be used
