### ISSUE TITLE
CLI conversion tool 

### ISSUE THREAD

**Issue by HuguesDelorme** [fougue/mayo#30]
Provide conversion tool through CLI(Command Line Interface).
Something like :
```bash
$> mayo file.step --export file.obj --export file.stl
```

Potential helpers :
https://github.com/p-ranav/indicators
https://github.com/ikalnytskyi/termcolor
https://github.com/prakhar1989/progress-cpp

This feature is also related to #56

**Comment by VictorLamoine** [comment]
Adding a precision switch (when applicable) would be great too. When exporting to STL I like to be able to choose the precision because it impacts 3D print quality on round features.

Or export in AMF which is a much smarter format :smile:

**Comment by HuguesDelorme** [comment]
@VictorLamoine 
> Adding a precision switch (when applicable) would be great too. When exporting to STL I like to be able to choose the precision because it impacts 3D print quality on round features.

Hello Victor, have a look at develop branch and the new feature about "meshing of BRep shapes"
Relates to https://github.com/fougue/mayo/issues/56 and https://github.com/fougue/mayo/issues/61 (show the amount of triangles)

**Comment by VictorLamoine** [comment]
I just tried the latest develop branch but I still experience https://github.com/fougue/mayo/issues/48 and have not time to try and fix this issue  at the moment sorry !

**Comment by VictorLamoine** [comment]
I just installed OpenCascade from `apt` and used it instead my own compiled version and everything now works.
Thanks for the command line tool it works great and is fast! 👍🏼
