### ISSUE TITLE
UTF-8 part name

### ISSUE THREAD

**Issue by VictorLamoine** [fougue/mayo#35]
Not sure if related to OpenCascade or Mayo but the part name displayed in Mayo does not support UTF-8 while the document name does:
![image](https://user-images.githubusercontent.com/5566160/99153935-3e83fd80-26ac-11eb-9040-1d00ca60e0dc.png)

I have noticed  OpenCascade 7.5.0 brings some UTF-8 improvements but for writing files.

**Comment by HuguesDelorme** [comment]
Hello Victor, thanks for reporting this issue. I could not reproduce the issue by manually editing(ie with a text editor) an instance name within a STEP file. Can you attach yours ?
Thanks !

**Comment by VictorLamoine** [comment]
Here is the example file: https://gofile.io/d/J3JsyD

**Comment by HuguesDelorme** [comment]
OK looking the STEP file reaveals that the name is really stored as "Petit \X\E9tui"
Have a look at line L7600 for example :
#7025=MANIFOLD_SOLID_BREP('Petit \X\E9tui',#7016);

I guess the encoding problem here comes from the software that generated this file(steptools from the header).
Same behavior in FreeCAD 0.18 as well.

**Comment by VictorLamoine** [comment]
Ah! I'm using OnShape I'll report the problem on their side then. I should have checked the file first.
