### ISSUE TITLE
Supporting Collada (.dae)

### ISSUE THREAD

**Issue by mantielero** [fougue/mayo#38]
This is already supported by FreeCAD, so I think that OpenCascade might already support this. I think is useful to export from STEP (CAD files) to Blender (for rendering) without relying on FreeCAD.

**Comment by HuguesDelorme** [comment]
As of OpenCascade 7.5.0 doesn't support Collada format.
From what I can see FreeCAD provide Collada import/export with `.../src/Mod/Arch/importDAE.py`
At first sight I would prefer to use [OpenCollada](https://github.com/KhronosGroup/OpenCOLLADA) or [Assimp](https://github.com/assimp/assimp) (by the way see #19)

**Comment by HuguesDelorme** [comment]
See as well fork https://github.com/RemiArnaud/OpenCOLLADA
