### ISSUE TITLE
Color a single component

### ISSUE THREAD

**Issue by SudatiSimone** [fougue/mayo#43]
Hi, 
I'm trying to add a new feature to the program. I would like to color a single selected item with the color I prefer.
Above all, I add this line:
```
 m_propertyReferredColor.setUserReadOnly(false);
```
In this way, I could choose the color.

<img src="https://user-images.githubusercontent.com/39488019/101924438-faafe580-3bd0-11eb-9f44-4e72587e9ed5.png" width="250" height="250">

<img src="https://user-images.githubusercontent.com/39488019/101925006-a9542600-3bd1-11eb-926c-b04cc8cad572.png" width="400" height="250">

<img src="https://user-images.githubusercontent.com/39488019/101925173-ddc7e200-3bd1-11eb-8605-46e36c2cd56c.png" width="250" height="250">

Now I want to ask you this great favor. 
1) It is possible to change also the component's color in response to the changes in the properties I did?
2) It is possible to make this change permanent? Because If I selected another component this change (the color I choose) disappears.

**Comment by HuguesDelorme** [comment]
Hello,
Yes this is possible, Mayo lets you edit the Name and Product Name properties, see function `XCaf_DocumentTreeNodePropertiesProvider::Properties::onPropertyChanged()` in file `src/app/document_tree_node_properties_providers.cpp` :
````c++
    void onPropertyChanged(Property* prop) override
    {
        if (prop == &m_propertyName)
            CafUtils::setLabelAttrStdName(m_label, m_propertyName.value());
        else if (prop == &m_propertyReferredName)
            CafUtils::setLabelAttrStdName(m_labelReferred, m_propertyReferredName.value());

        PropertyGroupSignals::onPropertyChanged(prop);
    }
````
I would add another `else if (prop == &m_propertyColor)` condition and assign the color.
The thing that needs a new mechanism is to update the 3D graphics of the entity. This needs a bit of thinking!
I will have a look in the next couple of days and let you know.

**Comment by SudatiSimone** [comment]
Thank you very much
I will be waiting for your reply

**Comment by SudatiSimone** [comment]
I try in this way but it gives me an error for the function's scope because the path is 
Mayo::(anonymous namespace)::propertyValueText(PropertyOccColor* prop) 
and It isn't accessible from other classes for the anonymous namespace.
In document_tree_node_properties_providers.cpp,  I add:
```cpp
 #include "../app/property_item_delegate.h"
```
and 
```cpp
   void onPropertyChanged(Property* prop) override
    {
        if (prop == &m_propertyName)
            CafUtils::setLabelAttrStdName(m_label, m_propertyName.value());
        else if (prop == &m_propertyReferredName)
            CafUtils::setLabelAttrStdName(m_labelReferred, m_propertyReferredName.value());
       else if (prop == &m_propertyReferredColor){
            QString new_color = Mayo::propertyValueText(m_propertyReferredColor);
            CafUtils::setLabelAttrStdName(m_labelReferred,new_color);
        }
        PropertyGroupSignals::onPropertyChanged(prop);
    }
```
  to use this function 
```cpp
static QString propertyValueText(const PropertyOccColor* prop) {
    return StringUtils::text(prop->value());
}
```

**Comment by HuguesDelorme** [comment]
Hello,
    Have a look at branch `feature/color` it implements the functionnality you described.
    There is a limitation though, as I described in some comments within the code changes.
    The supported color change applies only on the "product" shapes and not on the "instance" shapes.
    Mayo uses XCAFPrs_AISObject to display shape assemblies and this class put all shapes sharing the same "aspect style(including color)" into a shape compound. Supporting with XCAFPrs_AISObject the color change of an "instance" shape would imply to recompute whole 3D graphics of the assembly.
    I can do it also, that would interesting to see the impact.

**Comment by HuguesDelorme** [comment]
I'm thinking of a more flexible solution by using a hierarchy of `XCAFPrs_AISObject`s instead a of a single one.
Those objects would form a graph matching closely the model tree. Instance shapes would be displayed with `AIS_ConnectedInteractive` objects.

**Comment by SudatiSimone** [comment]
To understand If I realize the problem.
Now the changes that I made on the colour's component aren't permanent but If I close and re-open the file, there aren't my changes.  It's correct?

In my case, I want to open a step file, to do some changes (colour, name, attributes) and save the file with changes.
Maybe to solve the problem:
- open step file
- do changes
- file->export selected items (the root with stp extension) -> save as a new file with changes
Or also in this way, there is the same problem?

![image](https://user-images.githubusercontent.com/39488019/102490127-b4de9b80-406e-11eb-8f36-f1902a48fbf2.png)

Now I can't do it because It gives me this error when I try to save it.

**Comment by HuguesDelorme** [comment]
You get this error when trying the version in branch `feature/color` ?

**Comment by SudatiSimone** [comment]
In **default branch**: it works but non properly.
On the left the starter file. I change a name and I export the file. On the right the exported file.
<img src="https://user-images.githubusercontent.com/39488019/102505849-c6ca3980-4082-11eb-9604-780c67e8f276.png" width="400" height="300"> <img src="https://user-images.githubusercontent.com/39488019/102505924-dcd7fa00-4082-11eb-9887-147c7305f8f7.png" width="400" height="300">


In **feature/color branch** : it doesn't work and It gives me this error "Error during export to 'C:\....\name_file' File write problem".

**Comment by HuguesDelorme** [comment]
It might be caused by your Export/STEP settings.
Run `Tools->Options` and try to "Restore Defaults" or at least make sure that `Schema` option is set to `AP214_IS` as below :
![image](https://user-images.githubusercontent.com/939132/102507087-2543e780-4084-11eb-8d43-ca184765dca7.png)

**Comment by SudatiSimone** [comment]
Thanks again! 😍😍
With the trick of saving a new file with "Export selected items" I can create a new file with the changes I made. So the colour, name etc. that I choose is permanent!

In the next days, I will try to automatize it. Maybe with a simple "save" button that it does what "Export selected items" does. The save button will delete the old file and replace it with the new one

**Comment by SudatiSimone** [comment]
I have the last question. 
I understand how now it works: I can colour for product and not for a single instance of the objects.
My new question is: 
it is possible to colour a single surface of objects?
For example to colour only one of the six faces of a cube.
What I want to understand is if it is feasible and with how much effort.
Then I'd work on it myself.

Thanks again

**Comment by HuguesDelorme** [comment]
Yes this is possible, not yet directly with Mayo UI though.
You will need `XCAFDoc_ShapeTool` and `XCAFDoc_ColorTool` objects that you can access with `Mayo::Document::xcaf()` and `Mayo::XCaf::shapeTool/colorTool()`
Let's assume that the "cube" shape is stored in label `labelCube` in the document.
1. Declare the cube face `face` you want of a different color by a call to `XCAFDoc_ShapeTool::AddSubShape(labelCube, face)`. This will return the label `labelFace`
2. Call `XCAFDoc_ColorTool::SetColor(labelFace, color)`
3. Redisplay the 3D graphics

**Comment by HuguesDelorme** [comment]
Hello Simone,

    Not related to our problem but I would like to ask you the resolution in pixels of your screen, because from the screenshots you posted in this thread I saw that the 3D viewcube and some icons are very small.
    I'm preparing a fix for that issue.

Thanks !

**Comment by SudatiSimone** [comment]
Hi!
<img src="https://user-images.githubusercontent.com/39488019/103627614-2c9d3900-4f3e-11eb-89f4-20011d52bd06.png" width="300" height="100">
Looking at the technical specifications it says so but my feeling is that it's a lower resolution.
If you need some example's screens to see how It works on my pc I will send them to you.
