### ISSUE TITLE
Open file Error : IFSelect_RetError

### ISSUE THREAD

**Issue by sinfee** [fougue/mayo#45]
When I open this step file ,it got a error .
[jdzl-step.zip](https://github.com/fougue/mayo/files/5746208/jdzl-step.zip)

**Comment by HuguesDelorme** [comment]
Mayo currently doesn't support ZIP files, you have to extract first the files from the archive.
![image](https://user-images.githubusercontent.com/939132/103201767-000b7080-48f1-11eb-96c9-69ea5ccfe9cd.png)

**Comment by sinfee** [comment]
I know but I havn't find a way to upload a step file. so I zip it. 
I find the error is because my file is under a chinese name directory  . 
![image](https://user-images.githubusercontent.com/31951381/103263026-a5057680-49e1-11eb-9df8-2f795f499afc.png)

**Comment by HuguesDelorme** [comment]
Are you running a recent version of Mayo ? A couple of weeks ago I remember having adapted IO source code to use utf8 instead of local8bit for file paths.
Can you please check with latest version (in branch `develop`)
Let me know the result

**Comment by HuguesDelorme** [comment]
Just did this test with version as of commit 2ec8230164a7268f96eb757bd4c3e5c440b179ee + OpenCascade 7.4.0 on Windows10 : open a STEP file located in the folder `F:\dev\data\test-encoding\简化的中文命名目录测试`
No problem reported :
![image](https://user-images.githubusercontent.com/939132/103349027-05f18500-4a9c-11eb-9a52-e1bb8db934cf.png)

**Comment by sinfee** [comment]
Thanks for your help . I used release 0.2.0 . I will try current develop version.
