### ISSUE TITLE
Clipping planes: colors

### ISSUE THREAD

**Issue by VictorLamoine** [fougue/mayo#74]
When using clip planes on an assembly it's hard to differentiate the parts because all cut surfaces are colored in red:
![image](https://user-images.githubusercontent.com/5566160/121543058-ea09ec00-ca08-11eb-802f-a101788ea412.png)

What would be nice is to keep the surface colors and ideally add hatching lines like this:
![image](https://user-images.githubusercontent.com/5566160/121543149-fdb55280-ca08-11eb-8dfe-8ec15475e1bf.png)

Example assembly:
https://cad.onshape.com/documents/2ad871b0a5ef2c70b6d5d85f/w/885692aa77d2b4ead62ed359/e/044f794468440e956b6cb205

**Comment by HuguesDelorme** [comment]
Done with commit 6dd26ae but still "global" hatching and not per-solid hatching

**Comment by VictorLamoine** [comment]
Looks much better thanks!
![Screenshot_20220522_105845](https://user-images.githubusercontent.com/5566160/169687555-0a29b026-7548-44c1-94e9-51ffdabc7c75.png)
