### ISSUE TITLE
HiDPI

### ISSUE THREAD

**Issue by VictorLamoine** [fougue/mayo#97]
On high resolution screens the application does not display correctly:

Here on a laptop with a 2880x1800 screen resolution:
![Screenshot_20220204_133945](https://user-images.githubusercontent.com/5566160/152530945-9a41c06e-dc47-4287-9a0f-9f1e26d13262.png)

3D viewer is too small

Running `QT_SCALE_FACTOR=0.5 ./mayo`:
![Screenshot_20220204_133911](https://user-images.githubusercontent.com/5566160/152531030-70983023-1601-482f-b864-af539f7023eb.png)

Now the viewer is correctly sized but the text is very small.

https://doc.qt.io/qt-5/highdpi.html

**Comment by HuguesDelorme** [comment]
Thanks for reporting!
Duplicates #54

**Comment by HuguesDelorme** [comment]
@VictorLamoine 
Branch bugfix/highdpi is an attempt to fix high DPI support.
I don't have a suitable screen for real testing, I used QT_SCALE_FACTOR to simulate higher DPI.
It would be great if you have some time to check that branch works on your local machine!
Let me know any feedback
Greetings

**Comment by VictorLamoine** [comment]
Sorry for the late reply: It now works perfectly out of the box on a HDPI screen, good work 👍🏼

**Comment by HuguesDelorme** [comment]
Good news!
Many thanks for your feedback
